import type { Metadata } from "next";
import Image from "next/image";
import { BRAND } from "@/lib/brand";
import Mark from "@/components/brand/Mark";
import { SOURCE_CATALOG } from "@/lib/sources/catalog";
import { centroidByIso2 } from "@/lib/signals/country-centroids.data";
import GlobeStage from "@/components/marketing/GlobeStage";
import {
  AUDIT_COUNTRIES,
  AUDIT_LAYERS,
  AUDIT_MEASURED_AT,
  AUDIT_MEASURED_FROM,
  AUDIT_POLYGON_SOURCE,
  AUDIT_TIERS,
  AUDIT_TOTALS,
} from "@/lib/marketing/coverage-audit.data";
import {
  MOST_SURVEILLED,
  PUBLIC_SPEND,
  REPUTATION_CHECK,
  SURVEILLANCE_AVERAGE,
  SURVEILLANCE_CAVEAT,
  SURVEILLANCE_MAX,
  SURVEILLANCE_SOURCE,
} from "@/lib/marketing/surveillance.data";
import { CAMERA_FACTS } from "@/lib/marketing/camera-facts.data";
import { UNIT_TESTS } from "@/lib/marketing/repo-facts.data";

const REPO = "011-sam-110/Provenance";
const REPO_URL = `https://github.com/${REPO}`;

export const metadata: Metadata = {
  title: `${BRAND.name} · ${BRAND.tagline}`,
  description: BRAND.description,
  alternates: { canonical: "/" },
};

/**
 * The landing page.
 *
 * THE ONE RULE. Not a figure on this page is typed by hand. Everything countable comes
 * from one of three places, and each of them can be checked:
 *
 *   • `coverage-audit.data.ts` — generated by `scripts/gen-landing-audit.mjs` from a
 *     production run of `scripts/country-event-breakdown.mts`. Carries its own
 *     measurement date, which the page prints beside every figure taken from it.
 *   • `surveillance.data.ts` — one published study, at one scope, with the quote each
 *     row was read from recorded in `docs/LANDING_SOURCES.md`.
 *   • `repo-facts.data.ts` — measured against this tree, pinned by a test.
 *
 * `docs/LANDING_SOURCES.md` also records the figures that were REMOVED from the first
 * draft because no source carried them. That list is the more useful half.
 *
 * DEEP-LINK SHIM. Legacy `?v=`/`?c=` links are forwarded to /app by `redirects()` in
 * next.config.ts, NOT here. Reading `searchParams` in this component is what made the
 * whole page dynamic, so the shim was costing a server render on every visit to serve a
 * redirect almost nobody triggers. tests/unit/landing-static.test.ts guards both halves.
 * Do not reintroduce a `searchParams` prop on this page.
 */
export default async function Landing() {
  // Every registered signal layer, handed to the globe. Read here on the server rather
  // than imported by the globe itself: `SOURCE_CATALOG` pulls in `SIGNALS`, and `SIGNALS`
  // pulls in all ~39 adapter modules, none of which the browser needs in order to read
  // three strings off each entry.
  //
  // This is why the globe cannot drift from the product. A new adapter appears on the
  // globe from the same registry entry, with no marketing-side list to forget to update.
  const heroLayers = SOURCE_CATALOG.filter((s) => s.kind === "signal").map((s) => ({
    id: s.id,
    label: s.label,
    color: s.color,
  }));
  const satColor = SOURCE_CATALOG.find((s) => s.id === "satellites")?.color ?? "#7c3aed";

  // The land shading and the Coverage steps are the same measurement, so the picture and
  // the table cannot disagree.
  const shading = Object.fromEntries(AUDIT_COUNTRIES.map((c) => [c.iso2, c.layers]));
  const shadingMax = Math.max(...AUDIT_COUNTRIES.map((c) => c.layers));

  // The five best-covered countries, taken from the audit's own ordering rather than
  // chosen. If the measurement changes, this list changes with it.
  const topCovered = AUDIT_COUNTRIES.slice(0, 5);

  const measuredOn = new Date(AUDIT_MEASURED_AT);
  const measuredLabel = `${measuredOn.toISOString().slice(0, 10)} ${measuredOn
    .toISOString()
    .slice(11, 16)} UTC`;

  const tierCopy: Record<string, string> = {
    incidents:
      "Countries where something is happening right now: a quake, a fire, a flood, a protest, a jammed GPS cell, a military aircraft.",
    readings:
      "Countries carrying a measurement or an index: air quality, displacement totals, outage scores, the instability index.",
    assets:
      "Countries with permanent infrastructure mapped: airports, ports, reactors, cables and their landing stations.",
  };
  const tierName: Record<string, string> = {
    incidents: "Incidents",
    readings: "Readings",
    assets: "Assets",
  };

  const nf = new Intl.NumberFormat("en-GB");
  // The pin's label is built from the SAME row the step prints, so the globe can never
  // caption a figure the copy beside it does not say.
  const covPlaces = topCovered.map((c) => {
    const centroid = centroidByIso2(c.iso2);
    return {
      lon: centroid?.lon ?? 0,
      lat: centroid?.lat ?? 20,
      label: `${c.name.toUpperCase()}  ${c.layers} LAYERS`,
    };
  });
  const watchPlaces = MOST_SURVEILLED.map((p) => ({
    lon: p.lon,
    lat: p.lat,
    label: `${p.name.toUpperCase()}  ${p.per} PER 1,000`,
  }));

  return (
    <>
      <GlobeStage
        layers={heroLayers}
        satColor={satColor}
        coverage={shading}
        coverageMax={shadingMax}
        watchPlaces={watchPlaces}
        covPlaces={covPlaces}
      />

      <nav className="pv-nav" aria-label="Site">
        <a className="pv-nav-brand" href="#top">
          <Mark className="pv-nav-mark" size={22} />
          <span>{BRAND.name}</span>
        </a>
        <span className="pv-nav-rule" aria-hidden="true" />
        <span className="pv-nav-links">
          <a href="#watched">Watched</a>
          <a href="#coverage">Coverage</a>
          <a href="#layers">Layers</a>
          <a href="#why">Why</a>
          <a className="pv-nav-cta" href="/app">
            Open the map →
          </a>
        </span>
      </nav>

      {/* ── hero ─────────────────────────────────────────────────────────────────── */}
      <header className="pv-hero pv-intro" id="top">
        <div className="pv-hero-veil" aria-hidden="true" />
        <div className="pv-hero-copy">
          {/* Two spans, not a <br>: each line wipes up under its own clip, and a line
              break cannot carry an animation. */}
          <h1 className="pv-h1">
            <span>You already</span>
            <span>paid for this.</span>
          </h1>
          <p className="pv-hero-lede">
            The agencies that run the roads already publish their own cameras.{" "}
            <strong>
              {CAMERA_FACTS.feeds} operator feeds across {CAMERA_FACTS.countries} countries
            </strong>
            , and <strong>{nf.format(CAMERA_FACTS.webcams)}</strong> more webcams catalogued
            worldwide &mdash; public, live, and on a different website every time.{" "}
            {BRAND.name} draws them on one globe.
          </p>
          <div className="pv-cta-row">
            <a className="pv-cta" href="/app">
              Open the map
            </a>
            <a className="pv-cta pv-cta-ghost" href={REPO_URL} target="_blank" rel="noreferrer noopener">
              Read the source
            </a>
          </div>
        </div>

        <div className="pv-hero-strip">
          <div className="pv-hero-strip-inner">
            <p>
              {AUDIT_TOTALS.layers} layers · {AUDIT_TOTALS.live} live ·{" "}
              {nf.format(AUDIT_TOTALS.featuresPlaced)} features placed in{" "}
              {AUDIT_TOTALS.countriesTouched} countries · measured {measuredLabel}
            </p>
            <p className="pv-hero-strip-credit">
              Natural Earth · OpenFreeMap · OpenStreetMap · CelesTrak · USGS · NASA EONET
            </p>
          </div>
        </div>
      </header>

      {/* ── the public money ─────────────────────────────────────────────────────── */}
      <section className="pv-block pv-receipts" id="paid">
        <div className="pv-measure">
          <p className="pv-eyebrow">
            <span>The receipts</span>
            <span className="pv-sep">·</span>
            <span>Public budgets</span>
          </p>
          <h2 className="pv-h2">Three numbers, and where to check them.</h2>
        </div>
        <dl className="pv-receipt-grid">
          {PUBLIC_SPEND.map((s) => (
            <div className="pv-receipt" key={s.figure}>
              <dt className="pv-receipt-figure">{s.figure}</dt>
              <dd>
                <p className="pv-receipt-what">{s.what}</p>
                <p className="pv-receipt-detail">{s.detail}</p>
                <a href={s.url} target="_blank" rel="noreferrer noopener" className="pv-receipt-cite">
                  {s.source}
                </a>
              </dd>
            </div>
          ))}
        </dl>
      </section>

      {/* ── watched ──────────────────────────────────────────────────────────────── */}
      <section className="pv-block" id="watched">
        <div className="pv-watch-head">
          <div className="pv-measure">
            <p className="pv-eyebrow">
              <span>Surveillance</span>
              <span className="pv-sep">·</span>
              <span>Public CCTV per 1,000 people</span>
              <span className="pv-sep">·</span>
              <span>{SURVEILLANCE_SOURCE.updated}</span>
            </p>
            <h2 className="pv-h2">The most watched places on Earth.</h2>
            <p className="pv-lede">
              The five most surveilled places in Comparitech&rsquo;s study of the 150 largest
              cities, by public cameras per thousand residents. Keep scrolling: the globe turns
              to each one.
            </p>
            <p className="pv-prose">
              A camera that watches a road is infrastructure. A camera that watches a population
              is something else. This site shows road cameras because the public paid for them
              and can already see them; it does not point one at you, it does not keep a frame,
              and it never will.
            </p>
          </div>

          {/* The camera, cut out, looking down at the heading. Held at its natural 174px
              rather than filled to the column: it is a small source image, and upscaling it
              would put a soft, obviously-stretched object next to type this sharp. */}
          <div className="pv-camera">
            <div className="pv-camera-glow" aria-hidden="true" />
            <Image
              src="/marketing/cctv-camera.png"
              alt="A CCTV camera"
              width={174}
              height={161}
              className="pv-camera-img"
            />
            <span className="pv-graffiti pv-camera-tag" aria-hidden="true">
              WHO WATCHES THE WATCHERS?
            </span>
          </div>
        </div>

        <ol className="pv-steps">
          {MOST_SURVEILLED.map((place, i) => (
            <li className="pv-step" data-step={i} key={place.rank} style={{ opacity: i === 0 ? 1 : 0.3 }}>
              <span
                className="pv-graffiti pv-step-tag"
                aria-hidden="true"
                style={{
                  color: place.tagColor,
                  transform: `rotate(${place.tagRot})`,
                  textShadow: `0 0 12px ${place.tagColor}88`,
                  textDecoration: place.tagDeco ?? "none",
                }}
              >
                {place.tag}
              </span>
              <div className="pv-step-head">
                <span className="pv-step-rank">{place.rank}</span>
                <h3 className="pv-h3">{place.name}</h3>
                <span className="pv-step-country">{place.country}</span>
              </div>
              <div className="pv-step-figure">
                <span className="pv-bignum">{place.per}</span>
                <span className="pv-step-unit">public cameras per 1,000 people</span>
              </div>
              <div className="pv-bar">
                <i style={{ width: `${Math.round((place.perValue / SURVEILLANCE_MAX) * 100)}%` }} />
              </div>
              <dl className="pv-step-dl">
                <dt>Cameras</dt>
                <dd>{place.cameras}</dd>
                <dt>Population</dt>
                <dd>{place.population}</dd>
                {place.caveat ? (
                  <>
                    <dt>Read as</dt>
                    <dd>{place.caveat}</dd>
                  </>
                ) : null}
              </dl>
            </li>
          ))}
        </ol>

        <div className="pv-measure pv-watch-foot">
          <h3 className="pv-h3 pv-h3-loose">The cities with the reputation are not the cities that rank.</h3>
          <dl className="pv-reputation">
            {REPUTATION_CHECK.map((r) => (
              <div key={r.name}>
                <dt>{r.name}</dt>
                <dd>
                  <strong>{r.per}</strong> per 1,000 · {r.cameras} {r.note}
                </dd>
              </div>
            ))}
          </dl>
          <p className="pv-note">
            Across the cities studied the average is {SURVEILLANCE_AVERAGE.excludingChina} cameras
            per 1,000 people, or {SURVEILLANCE_AVERAGE.includingChina} once China is included.
            Every figure in this section is public CCTV only — cameras operated by government
            bodies — and mixing it with a total-installed-base estimate, which counts private and
            commercial cameras too, produces a ranking where nothing is comparable to anything
            else. The study&rsquo;s own caveat: &ldquo;{SURVEILLANCE_CAVEAT}&rdquo;{" "}
            <a href={SURVEILLANCE_SOURCE.url} target="_blank" rel="noreferrer noopener">
              {SURVEILLANCE_SOURCE.publisher}, {SURVEILLANCE_SOURCE.updated}
            </a>
            .
          </p>
        </div>
      </section>

      {/* ── why ──────────────────────────────────────────────────────────────────── */}
      <section className="pv-block pv-why" id="why">
        <div className="pv-measure">
          <p className="pv-eyebrow">
            <span>Why this exists</span>
            <span className="pv-sep">·</span>
            <span>Built by students</span>
          </p>
          <h2 className="pv-h2">Built by students. Kept free.</h2>
          <p className="pv-lede">
            {BRAND.name} was built by university students at the start of our careers. It is free
            for anyone to use, it stays open source so anyone can contribute, and it exists
            because we believe this data should be far easier to reach than it is today.
          </p>
        </div>
        <dl className="pv-ledger">
          <div>
            <dt>Cost to use</dt>
            <dd>£0</dd>
          </div>
          <div>
            <dt>Login</dt>
            <dd>none</dd>
          </div>
          <div>
            <dt>Licence</dt>
            <dd>{BRAND.license.short}</dd>
          </div>
          <div>
            <dt>Unit tests</dt>
            <dd>
              {nf.format(UNIT_TESTS.cases)} across {UNIT_TESTS.files} files
            </dd>
          </div>
          <div>
            <dt>Source</dt>
            <dd>
              <a href={REPO_URL} target="_blank" rel="noreferrer noopener">
                {REPO}
              </a>
            </dd>
          </div>
          <div>
            <dt>Contribute</dt>
            <dd>
              <a href={`${REPO_URL}/pulls`} target="_blank" rel="noreferrer noopener">
                Open a pull request
              </a>
            </dd>
          </div>
        </dl>
      </section>

      {/* ── coverage ─────────────────────────────────────────────────────────────── */}
      <section className="pv-block pv-coverage" id="coverage">
        <div className="pv-measure">
          <p className="pv-eyebrow">
            <span>Coverage audit</span>
            <span className="pv-sep">·</span>
            <span>Measured {measuredLabel}</span>
            <span className="pv-sep">·</span>
            <span>{AUDIT_TOTALS.countriesTouched} countries</span>
          </p>
          <h2 className="pv-h2">What we actually have, country by country.</h2>
          <p className="pv-prose">
            Every one of the {AUDIT_TOTALS.layers} registered signal layers, read from{" "}
            {AUDIT_MEASURED_FROM.replace(/^https:\/\//, "")}, with each feature resolved to a
            country. The globe is shaded by how many layers place at least one feature in each
            country. This is the ground truth behind any coverage claim this page makes,
            including the parts that do not flatter it.
          </p>
          <div className="pv-legend">
            <span className="pv-legend-swatch pv-legend-none" />
            <span>No data</span>
            <span className="pv-legend-swatch pv-legend-ramp" />
            <span>1 to {shadingMax} layers</span>
          </div>
        </div>

        <div className="pv-tiers">
          {AUDIT_TIERS.map((t) => (
            <div className="pv-tier" key={t.tier}>
              <div className="pv-tier-figure">
                <span className="pv-tier-name">{tierName[t.tier]}</span>
                <div className="pv-tier-count">
                  <span className="pv-bignum pv-bignum-sm">{t.countries}</span>
                  <span className="pv-tier-of">/ {AUDIT_TOTALS.countriesTouched}</span>
                </div>
              </div>
              <div className="pv-tier-body">
                <div className="pv-bar">
                  <i style={{ width: `${Math.round((t.countries / AUDIT_TOTALS.countriesTouched) * 100)}%` }} />
                </div>
                <p>{tierCopy[t.tier]}</p>
                <span className="pv-tier-features">{nf.format(t.features)} features placed</span>
              </div>
            </div>
          ))}
        </div>

        <div className="pv-measure pv-cov-steps" data-pv-cov>
          <p className="pv-eyebrow">
            <span>Five countries</span>
            <span className="pv-sep">·</span>
            <span>Ranked by layers present</span>
          </p>
          <h2 className="pv-h2">Where the map is thickest.</h2>
          <p className="pv-lede">
            The five countries the most layers reach, and what each tier is actually made of
            there. The globe turns to each one.
          </p>
          <ol className="pv-steps">
            {topCovered.map((c, i) => (
              <li className="pv-step" data-cov={i} key={c.iso2} style={{ opacity: i === 0 ? 1 : 0.3 }}>
                <div className="pv-step-head">
                  <span className="pv-step-rank">{c.iso2}</span>
                  <h3 className="pv-h3">{c.name}</h3>
                  <span className="pv-step-country">{c.subregion}</span>
                </div>
                <div className="pv-step-figure">
                  <span className="pv-bignum">{c.layers}</span>
                  <span className="pv-step-unit">
                    of {AUDIT_TOTALS.layers} layers place a feature here
                  </span>
                </div>
                <dl className="pv-cov-dl">
                  <div>
                    <dt className="pv-t-inc">Incidents</dt>
                    <dd>
                      {c.incidents > 0
                        ? `${nf.format(c.incidents)} from ${c.incLayers} ${c.incLayers === 1 ? "layer" : "layers"}`
                        : "None"}
                    </dd>
                  </div>
                  <div>
                    <dt className="pv-t-read">Readings</dt>
                    <dd>
                      {c.readings > 0
                        ? `${nf.format(c.readings)} from ${c.readLayers} ${c.readLayers === 1 ? "layer" : "layers"}`
                        : "None"}
                    </dd>
                  </div>
                  <div>
                    <dt className="pv-t-asset">Assets</dt>
                    <dd>
                      {c.assets > 0
                        ? `${nf.format(c.assets)} from ${c.assetLayers} ${c.assetLayers === 1 ? "layer" : "layers"}`
                        : "None"}
                    </dd>
                  </div>
                </dl>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* ── layers ───────────────────────────────────────────────────────────────── */}
      <section className="pv-block" id="layers">
        <div className="pv-measure">
          <p className="pv-eyebrow">
            <span>The {AUDIT_TOTALS.layers} layers</span>
            <span className="pv-sep">·</span>
            <span>{AUDIT_TOTALS.live} live</span>
            <span className="pv-sep">·</span>
            <span>{AUDIT_TOTALS.partial} partial</span>
            <span className="pv-sep">·</span>
            <span>{AUDIT_TOTALS.down} broken</span>
            <span className="pv-sep">·</span>
            <span>{AUDIT_TOTALS.locked} locked</span>
          </p>
          <h2 className="pv-h2">Every layer, read from production.</h2>
          <p className="pv-lede">
            Where a layer is capped, the cap is declared: how many rows existed upstream, how
            many are here, and how the survivors were chosen.
          </p>
        </div>

        <div className="pv-table-wrap">
          <table className="pv-table">
            <thead>
              <tr>
                <th scope="col">Layer</th>
                <th scope="col">Group</th>
                <th scope="col">Tier</th>
                <th scope="col" className="pv-num">
                  Features
                </th>
                <th scope="col" className="pv-num">
                  Countries
                </th>
                <th scope="col">State</th>
              </tr>
            </thead>
            <tbody>
              {AUDIT_LAYERS.map((l) => (
                <tr key={l.id}>
                  <td>
                    {l.label}
                    {l.note ? <span className="pv-td-note">{l.note}</span> : null}
                  </td>
                  <td className="pv-td-dim">{l.group}</td>
                  <td className="pv-td-dim">{tierName[l.tier]}</td>
                  <td className="pv-num">{nf.format(l.features)}</td>
                  <td className="pv-num">{l.countries}</td>
                  <td>
                    <span className="pv-state" data-state={l.state}>
                      <i aria-hidden="true" />
                      {l.state}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="pv-note pv-measure">
          Countries = distinct countries the layer places at least one feature in.{" "}
          {AUDIT_TOTALS.spanningLayers.join(" and ")} carry line or area geometry, so they are
          counted in every country the shape touches and their per-country figures overlap. Of
          the {nf.format(AUDIT_TOTALS.featuresServed)} features served,{" "}
          {nf.format(AUDIT_TOTALS.featuresPlaced)} resolved to a country and{" "}
          {nf.format(AUDIT_TOTALS.featuresUnplaced)} were at sea, in orbit, or in a country too
          small for the boundary file. Measured by{" "}
          <a
            href={`${REPO_URL}/blob/main/scripts/country-event-breakdown.mts`}
            target="_blank"
            rel="noreferrer noopener"
          >
            scripts/country-event-breakdown.mts
          </a>{" "}
          against /api/signals/&lt;id&gt; on production. Country resolution uses {AUDIT_POLYGON_SOURCE}.
        </p>
      </section>

      {/* ── handoff ──────────────────────────────────────────────────────────────── */}
      <section className="pv-handoff" id="handoff">
        <div className="pv-handoff-inner">
          <p className="pv-eyebrow">
            <span>The map</span>
            <span className="pv-sep">·</span>
            <span>No login</span>
            <span className="pv-sep">·</span>
            <span>No key</span>
          </p>
          <h2 className="pv-h2">Everything above was this.</h2>
          <p className="pv-lede">
            The globe behind this page is the product, running, on live data. The rest of it is
            one click away.
          </p>
          <div className="pv-cta-row">
            <a className="pv-cta" href="/app">
              Open the map
            </a>
            <a className="pv-cta pv-cta-ghost" href={REPO_URL} target="_blank" rel="noreferrer noopener">
              Read the source
            </a>
          </div>
        </div>
      </section>

      <footer className="pv-footer">
        <div className="pv-footer-inner">
          <div>
            <h4>{BRAND.name}</h4>
            <p>{BRAND.description}</p>
          </div>
          <div>
            <h4>The product</h4>
            <a href="/app">Open the map</a>
            <a href="#coverage">Coverage by country</a>
            <a href="#layers">All {AUDIT_TOTALS.layers} layers</a>
            <a href={BRAND.discordUrl} target="_blank" rel="noreferrer noopener">
              Discord
            </a>
            <a href="/privacy">Privacy</a>
          </div>
          <div>
            <h4>The code</h4>
            <a href={REPO_URL} target="_blank" rel="noreferrer noopener">
              GitHub
            </a>
            <a href={`${REPO_URL}/blob/main/docs/API_KEYS.md`} target="_blank" rel="noreferrer noopener">
              Which layers need a key
            </a>
            <a href={`${REPO_URL}/blob/main/docs/LANDING_SOURCES.md`} target="_blank" rel="noreferrer noopener">
              Sources for every figure here
            </a>
            <a href={BRAND.license.url} target="_blank" rel="noreferrer noopener">
              Licence ({BRAND.license.short})
            </a>
            <a href={BRAND.kofiUrl} target="_blank" rel="noreferrer noopener">
              Support the running costs
            </a>
          </div>
          <div>
            {/* TWO faces now, so two credits. This list named Archivo, Public Sans and IBM
                Plex Mono long after they were dropped; leaving a face here that the page does
                not load — or omitting one it does — is a visible false statement on a page
                whose argument is that its claims are checkable. */}
            <h4>Typefaces</h4>
            <a href="https://fonts.google.com/specimen/Inter" target="_blank" rel="noreferrer noopener">
              Inter
            </a>
            <a
              href="https://fonts.google.com/specimen/Permanent+Marker"
              target="_blank"
              rel="noreferrer noopener"
            >
              Permanent Marker
            </a>
          </div>
          <div className="pv-footer-attr">
            <h4>Attribution</h4>
            <p>
              Powered by TfL Open Data. Webcams provided by Windy.com. Basemap © OpenFreeMap, ©
              OpenMapTiles, data from © OpenStreetMap contributors. Contains public sector
              information licensed under the Open Government Licence. Country outlines on this
              page: Natural Earth 110m (public domain). Star catalogue:{" "}
              <a href="https://codeberg.org/astronexus/hyg" target="_blank" rel="noreferrer noopener">
                HYG database v4.4
              </a>{" "}
              by David Nash (astronexus), licensed CC BY-SA 4.0. Star positions are real; the sky
              is shown at a wider angle than the globe&rsquo;s own camera so whole constellations
              fit the frame.
            </p>
            <p>
              © {BRAND.license.year} {BRAND.license.holder}. {BRAND.name} is free software under
              the {BRAND.license.name}. The data above keeps its own separate terms.
            </p>
          </div>
        </div>
      </footer>
    </>
  );
}
