import type { SurfaceReading } from "@/lib/cameras/surface";

// Fintraffic road-weather sensors, keyed by WEATHER STATION id (not camera id — the
// join to a camera lives in digitraffic.join.data.ts, generated by the operator's own
// nearestWeatherStationId, not guessed here).
//
// ONE RULE MATTERS MORE THAN ANY OTHER IN THIS FILE: `state` is always
// `sensorValueDescriptionEn` VERBATIM. Fintraffic's KELI vocabulary is not fixed —
// "Dry"/"Moist"/"Wet" is what a September capture happened to see, and a winter
// station can and does report others ("Snow-covered", "Ice") with no warning to us.
// A `1 -> "Dry"` map would silently drop every value it was never told about, and the
// failure would look like nothing: the sensor keeps reporting, the number keeps
// changing, and the UI keeps saying "Dry" (or nothing) regardless. There is a
// synthetic KELI_1=4.0/"Snow-covered" row in the test fixture for exactly this reason
// — the fix if that test fails is to delete the map, never to extend it.

const KELI_NAMES = ["KELI_1", "KELI_2", "KELI_3"] as const;
const FLAG = /fault|error|missing/i;

interface SensorValue {
  name?: string;
  value?: number;
  sensorValueDescriptionEn?: string | null;
}

interface WeatherStation {
  id?: number;
  dataUpdatedTime?: string;
  sensorValues?: SensorValue[];
}

interface WeatherStationsResponse {
  dataUpdatedTime?: string;
  stations?: WeatherStation[];
}

function findSensor(values: SensorValue[], name: string): SensorValue | undefined {
  return values.find((v) => v.name === name);
}

/**
 * One station's sensor list → a SurfaceReading, or undefined when it has no KELI_*
 * sensor at all (no entry beats a fabricated "unknown" entry).
 *
 * Prefers KELI_1, falling back to KELI_2 then KELI_3 — Fintraffic reports several
 * road-condition sensors per station and KELI_1 is the primary. `km` and `station`
 * are intentionally left unset; the join layer (digitraffic.ts) supplies those from
 * the operator-declared pairing, which this pure function knows nothing about.
 */
export function normalizeStationReading(station: WeatherStation): SurfaceReading | undefined {
  const values = station.sensorValues ?? [];
  const keli = KELI_NAMES.map((n) => findSensor(values, n)).find((v) => v !== undefined);
  if (!keli) return undefined;

  const description = (keli.sensorValueDescriptionEn ?? "").toString();
  const reading: SurfaceReading = { state: description };

  const isFault = keli.value === 0 || FLAG.test(description);
  if (isFault) reading.operatorFlag = description;

  const tie1 = findSensor(values, "TIE_1");
  if (Number.isFinite(tie1?.value)) reading.roadTempC = tie1!.value as number;

  const ilma = findSensor(values, "ILMA");
  if (Number.isFinite(ilma?.value)) reading.airTempC = ilma!.value as number;

  const observedAt = Date.parse(station.dataUpdatedTime ?? "");
  if (Number.isFinite(observedAt)) reading.observedAt = observedAt;

  return reading;
}

/**
 * The bulk `/api/weather/v1/stations/data` response → a Map keyed by weather-station
 * id. PURE — no fetch here, so this is testable straight off the fixture.
 */
export function normalizeRoadWeather(json: WeatherStationsResponse): Map<number, SurfaceReading> {
  const out = new Map<number, SurfaceReading>();
  for (const station of json.stations ?? []) {
    const id = station.id;
    if (!Number.isFinite(id)) continue;
    const reading = normalizeStationReading(station);
    if (reading) out.set(id as number, reading);
  }
  return out;
}

/**
 * Fetches every Fintraffic road-weather station in one request (~528 stations,
 * ~360KB). NEVER THROWS — a failure here must not take the camera feed down with it,
 * so it resolves to an empty Map and logs instead. `digitraffic.ts` still wraps its
 * call in a try/catch as a second layer, since "this function promises not to throw"
 * is a promise, not a guarantee against every future edit.
 */
export async function fetchRoadWeather(): Promise<Map<number, SurfaceReading>> {
  try {
    const res = await fetch("https://tie.digitraffic.fi/api/weather/v1/stations/data", {
      headers: {
        // Mandatory — tie.digitraffic.fi 406s without it (see lib/sources/digitraffic.ts).
        "Accept-Encoding": "gzip",
        "Digitraffic-User": "TrafficNerd/2.0 (+github.com/011-sam-110/TrafficNerd-V2)",
      },
      signal: AbortSignal.timeout(15_000),
    });
    if (!res.ok) {
      console.warn(`Digitraffic road weather: ${res.status}`);
      return new Map();
    }
    const json = (await res.json()) as WeatherStationsResponse;
    return normalizeRoadWeather(json);
  } catch (e) {
    console.warn("Digitraffic road weather fetch failed:", e);
    return new Map();
  }
}
