/**
 * Every camera network that discovery proposed and a human admitted.
 *
 * GENERATED by `POST /api/admin/promote` from `data/discovery/ledger.json`. Edit the
 * ledger and re-run rather than editing this file, or the next promotion silently
 * reverts you. It is committed rather than built because a camera network appearing on
 * the map should be a reviewable diff in a pull request.
 *
 * THIS FILE IS THE GATE. `lib/sources/discovered.ts` serves exactly what is listed
 * here and nothing else, and the only way a row lands here is a reviewer working
 * through `/admin/verify` one camera at a time and then pressing promote. There is no
 * automatic path from a crawl to a pin on the map, by construction rather than by
 * policy.
 *
 * HOW TO READ A ROW. `review` says who admitted it, when, and how many cameras they
 * actually opened — `sampled` counts pictures looked at, not rows validated. `blocked`
 * lists native ids a reviewer rejected individually, so one dead camera costs one
 * camera rather than the network. `license` is copied from what the operator or its
 * catalogue states; where nothing is stated it says so in those words, because a
 * licence nobody granted is worse than an absent one.
 */

import type { AdmittedFeed } from "@/lib/discovery/types";

export const ADMITTED_FEEDS: AdmittedFeed[] = [
  {
    "key": "houston-transtar",
    "name": "Houston TranStar",
    "country": "US",
    "endpoint": "https://services.arcgis.com/NummVBqZSIJKUeVR/arcgis/rest/services/Trantar_Camera_Locations/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json&resultRecordCount=1000",
    "format": "arcgis",
    "mapping": {
      "lat": "__lat",
      "lon": "__lon",
      "name": "Name",
      "id": "OBJECTID",
      "road": "roadway",
      "imageUrl": "URL"
    },
    "license": "City of Houston GIS states no licence for this data (catalogue records: none)",
    "attribution": "Live camera imagery © Houston TranStar",
    "refreshSeconds": 300,
    "upgradeMediaToHttps": true,
    "homepage": "https://www.houstontranstar.org/",
    "review": {
      "by": "011-sam-110",
      "at": "2026-08-20T12:13:25.048Z",
      "sampled": 12,
      "good": 12
    }
  }
];
