import type { MetadataRoute } from "next";
import { BRAND } from "@/lib/brand";

// PWA web app manifest (Next metadata route → /manifest.webmanifest, and Next
// auto-injects the <link rel="manifest">). `display: standalone` makes it
// installable as a desktop/mobile app.
//
// Icons are the committed marks under public/icons, generated by
// scripts/gen-icons.mjs from lib/brand/markPaths.json — the same traced geometry
// components/brand/Mark.tsx renders. That shared source is the point: these icons
// spent seven weeks showing a teal globe the product had already replaced.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${BRAND.name} · live global intelligence`,
    short_name: BRAND.name,
    description: BRAND.description,
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "any",
    // The Terminal's near-black chrome, not the retired teal. These are the
    // colours the OS paints around an installed app — the splash ground and the
    // task-switcher tint — so leaving them on the old identity meant the
    // installed app opened teal and then became the Terminal.
    background_color: "#06080b",
    theme_color: "#06080b",
    categories: ["travel", "navigation", "utilities"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
