// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Written by scripts/gen-landing-audit.mjs from one run of scripts/country-event-breakdown.mts.
// Every figure the landing page states about coverage comes from here, so that a reader who
// doubts a number on the page can read the run that produced it rather than trust it.
//
// To refresh: re-run the breakdown against production, then
//   node scripts/gen-landing-audit.mjs <measurement.json>
//
// tests/unit/landing-audit.test.ts fails if the layer ids here drift from the live SIGNALS
// registry — adding a signal layer makes this file stale, and the test says so out loud
// rather than letting the page quietly understate itself.

/** When the measurement ran. Shown on the page beside every figure taken from it. */
export const AUDIT_MEASURED_AT = "2026-09-08T11:40:32.502Z";
/** What it was measured against. Production, not a laptop. */
export const AUDIT_MEASURED_FROM = "https://provenance-online.vercel.app";
/** How a feature was resolved to a country, and the limitation that carries. */
export const AUDIT_POLYGON_SOURCE = "Natural Earth 110m (public/geo/countries-110m.geojson), 177 polygons";

export type AuditTier = "incidents" | "readings" | "assets";
export type AuditState = "live" | "partial" | "down" | "locked";

export interface AuditLayer {
  id: string;
  label: string;
  group: string;
  tier: AuditTier;
  /** Features the layer actually served, which for a capped layer is not its upstream total. */
  features: number;
  /** Of those, how many resolved to a country. The rest are at sea, in orbit, or micro-states. */
  placed: number;
  /** Distinct countries the layer places at least one feature in. */
  countries: number;
  /**
   * Line or area geometry, so one feature is counted in every country its shape touches.
   * Per-country figures for these layers overlap and must not be summed into a feature total.
   */
  spansCountries: boolean;
  state: AuditState;
  /** The cap rule, the upstream's refusal, and how many features landed at sea or in orbit. */
  note: string;
}

export interface AuditCountry {
  iso2: string;
  name: string;
  subregion: string;
  /** Distinct layers placing at least one feature here. */
  layers: number;
  incidents: number;
  incLayers: number;
  readings: number;
  readLayers: number;
  assets: number;
  assetLayers: number;
}

export interface AuditTierTotal {
  tier: AuditTier;
  /** Countries where this tier places at least one feature. */
  countries: number;
  features: number;
}

export const AUDIT_LAYERS: AuditLayer[] = [
  {
    "id": "instability",
    "label": "Country Instability Index",
    "group": "Synthesis",
    "tier": "readings",
    "features": 173,
    "placed": 173,
    "countries": 173,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "earthquakes",
    "label": "Earthquakes",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 184,
    "placed": 178,
    "countries": 13,
    "spansCountries": false,
    "state": "live",
    "note": "6 at sea or in orbit."
  },
  {
    "id": "wildfires",
    "label": "Wildfires",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 94,
    "placed": 94,
    "countries": 1,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "volcanoes",
    "label": "Volcanoes",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 32,
    "placed": 32,
    "countries": 16,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "severeStorms",
    "label": "Severe storms",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 6,
    "placed": 2,
    "countries": 2,
    "spansCountries": false,
    "state": "live",
    "note": "4 at sea or in orbit."
  },
  {
    "id": "floods",
    "label": "Floods",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 80,
    "placed": 78,
    "countries": 37,
    "spansCountries": false,
    "state": "live",
    "note": "2 at sea or in orbit."
  },
  {
    "id": "gdacs",
    "label": "Disaster alerts",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 54,
    "placed": 53,
    "countries": 24,
    "spansCountries": false,
    "state": "partial",
    "note": "partial: TC failed (timeout). 1 at sea or in orbit."
  },
  {
    "id": "tropical-cyclones",
    "label": "Tropical cyclones (NHC)",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 2,
    "placed": 0,
    "countries": 0,
    "spansCountries": false,
    "state": "live",
    "note": "2 at sea or in orbit."
  },
  {
    "id": "fire-active",
    "label": "Active fires (FIRMS)",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 0,
    "placed": 0,
    "countries": 0,
    "spansCountries": false,
    "state": "down",
    "note": "Upstream answered http 400."
  },
  {
    "id": "emsc-quakes",
    "label": "Earthquakes (EMSC)",
    "group": "Natural hazards",
    "tier": "incidents",
    "features": 500,
    "placed": 430,
    "countries": 44,
    "spansCountries": false,
    "state": "live",
    "note": "Showing 500 of 500+, the first page the EMSC FDSN service returned. 70 at sea or in orbit."
  },
  {
    "id": "aurora",
    "label": "Aurora",
    "group": "Space weather",
    "tier": "readings",
    "features": 400,
    "placed": 204,
    "countries": 7,
    "spansCountries": false,
    "state": "live",
    "note": "Showing 400 of 508, the highest visibility probability. 196 at sea or in orbit."
  },
  {
    "id": "space-weather",
    "label": "Space weather (NOAA Kp/storms)",
    "group": "Space weather",
    "tier": "readings",
    "features": 1,
    "placed": 1,
    "countries": 1,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "launches",
    "label": "Rocket launches",
    "group": "Space",
    "tier": "assets",
    "features": 30,
    "placed": 29,
    "countries": 9,
    "spansCountries": false,
    "state": "live",
    "note": "Showing 30 of 358, the soonest — Launch Library 2 returns them in launch order. 1 at sea or in orbit."
  },
  {
    "id": "cables",
    "label": "Submarine cables",
    "group": "Infrastructure",
    "tier": "assets",
    "features": 707,
    "placed": 644,
    "countries": 129,
    "spansCountries": true,
    "state": "live",
    "note": "63 at sea or in orbit."
  },
  {
    "id": "cable-landings",
    "label": "Cable landing stations",
    "group": "Infrastructure",
    "tier": "assets",
    "features": 1925,
    "placed": 1908,
    "countries": 179,
    "spansCountries": false,
    "state": "live",
    "note": "17 at sea or in orbit."
  },
  {
    "id": "gpsJamming",
    "label": "GPS jamming",
    "group": "Infrastructure",
    "tier": "incidents",
    "features": 400,
    "placed": 366,
    "countries": 32,
    "spansCountries": true,
    "state": "live",
    "note": "Showing 400 of 518, the worst by interference ratio. 34 at sea or in orbit."
  },
  {
    "id": "nuclear",
    "label": "Nuclear plants",
    "group": "Infrastructure",
    "tier": "assets",
    "features": 216,
    "placed": 216,
    "countries": 36,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "airports",
    "label": "Major airports",
    "group": "Infrastructure",
    "tier": "assets",
    "features": 1173,
    "placed": 1081,
    "countries": 169,
    "spansCountries": false,
    "state": "live",
    "note": "92 at sea or in orbit."
  },
  {
    "id": "ports",
    "label": "Major ports",
    "group": "Infrastructure",
    "tier": "assets",
    "features": 71,
    "placed": 71,
    "countries": 40,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "internet-outages",
    "label": "Internet outages (IODA)",
    "group": "Infrastructure",
    "tier": "readings",
    "features": 17,
    "placed": 17,
    "countries": 17,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "cloud-status",
    "label": "Cloud & platform outages",
    "group": "Infrastructure",
    "tier": "incidents",
    "features": 5,
    "placed": 5,
    "countries": 1,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "conflict",
    "label": "Conflict coverage",
    "group": "Intel",
    "tier": "incidents",
    "features": 72,
    "placed": 72,
    "countries": 70,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "ukraineAlerts",
    "label": "Ukraine air-raid alerts",
    "group": "Conflict",
    "tier": "incidents",
    "features": 1,
    "placed": 1,
    "countries": 1,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "protests",
    "label": "Protest coverage",
    "group": "Intel",
    "tier": "incidents",
    "features": 21,
    "placed": 21,
    "countries": 21,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "airquality",
    "label": "Air quality",
    "group": "Environment",
    "tier": "readings",
    "features": 49,
    "placed": 49,
    "countries": 41,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "air-quality-stations",
    "label": "Air quality — stations (OpenAQ)",
    "group": "Environment",
    "tier": "readings",
    "features": 931,
    "placed": 904,
    "countries": 61,
    "spansCountries": false,
    "state": "live",
    "note": "Showing 931 of 931+, the first page OpenAQ returned — not a ranking. 27 at sea or in orbit."
  },
  {
    "id": "crime",
    "label": "UK street crime",
    "group": "Civic safety",
    "tier": "incidents",
    "features": 1500,
    "placed": 1500,
    "countries": 1,
    "spansCountries": false,
    "state": "live",
    "note": "Showing 1,500 of 11,181, the first found in city order (London, Manchester, Birmingham, Leeds, Liverpool, Bristol) — not a ranking."
  },
  {
    "id": "cyber-c2",
    "label": "Botnet C2 servers",
    "group": "Cyber threat",
    "tier": "readings",
    "features": 3,
    "placed": 3,
    "countries": 3,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "cyber-ransomware",
    "label": "Ransomware victims",
    "group": "Cyber threat",
    "tier": "readings",
    "features": 0,
    "placed": 0,
    "countries": 0,
    "spansCountries": false,
    "state": "down",
    "note": "Upstream answered http 404."
  },
  {
    "id": "displacement",
    "label": "Forced displacement",
    "group": "Human cost",
    "tier": "readings",
    "features": 171,
    "placed": 171,
    "countries": 171,
    "spansCountries": false,
    "state": "live",
    "note": ""
  },
  {
    "id": "reliefweb",
    "label": "Humanitarian emergencies (ReliefWeb)",
    "group": "Human cost",
    "tier": "readings",
    "features": 0,
    "placed": 0,
    "countries": 0,
    "spansCountries": false,
    "state": "locked",
    "note": "Needs a credential we do not hold."
  },
  {
    "id": "grid-load",
    "label": "Electricity grid load (ENTSO-E)",
    "group": "Infrastructure",
    "tier": "readings",
    "features": 0,
    "placed": 0,
    "countries": 0,
    "spansCountries": false,
    "state": "locked",
    "note": "Needs a credential we do not hold."
  },
  {
    "id": "military-air",
    "label": "Military flights",
    "group": "Military",
    "tier": "incidents",
    "features": 147,
    "placed": 134,
    "countries": 36,
    "spansCountries": false,
    "state": "live",
    "note": "13 at sea or in orbit."
  },
  {
    "id": "ais",
    "label": "Ships (AIS chokepoints)",
    "group": "Maritime",
    "tier": "incidents",
    "features": 51,
    "placed": 48,
    "countries": 9,
    "spansCountries": false,
    "state": "live",
    "note": "3 at sea or in orbit."
  }
];

export const AUDIT_COUNTRIES: AuditCountry[] = [
  {
    "iso2": "US",
    "name": "United States",
    "subregion": "Northern America",
    "layers": 22,
    "incidents": 318,
    "incLayers": 10,
    "readings": 225,
    "readLayers": 6,
    "assets": 444,
    "assetLayers": 6
  },
  {
    "iso2": "GB",
    "name": "United Kingdom",
    "subregion": "Northern Europe",
    "layers": 15,
    "incidents": 1532,
    "incLayers": 5,
    "readings": 29,
    "readLayers": 5,
    "assets": 212,
    "assetLayers": 5
  },
  {
    "iso2": "RU",
    "name": "Russian Federation",
    "subregion": "Eastern Europe",
    "layers": 15,
    "incidents": 90,
    "incLayers": 6,
    "readings": 52,
    "readLayers": 4,
    "assets": 103,
    "assetLayers": 5
  },
  {
    "iso2": "TR",
    "name": "Turkey",
    "subregion": "Western Asia",
    "layers": 15,
    "incidents": 164,
    "incLayers": 6,
    "readings": 25,
    "readLayers": 4,
    "assets": 31,
    "assetLayers": 5
  },
  {
    "iso2": "FR",
    "name": "France",
    "subregion": "Western Europe",
    "layers": 15,
    "incidents": 25,
    "incLayers": 5,
    "readings": 42,
    "readLayers": 4,
    "assets": 114,
    "assetLayers": 6
  },
  {
    "iso2": "IN",
    "name": "India",
    "subregion": "Southern Asia",
    "layers": 15,
    "incidents": 12,
    "incLayers": 6,
    "readings": 25,
    "readLayers": 4,
    "assets": 102,
    "assetLayers": 5
  },
  {
    "iso2": "JP",
    "name": "Japan",
    "subregion": "Eastern Asia",
    "layers": 14,
    "incidents": 10,
    "incLayers": 4,
    "readings": 7,
    "readLayers": 5,
    "assets": 165,
    "assetLayers": 5
  },
  {
    "iso2": "ES",
    "name": "Spain",
    "subregion": "Southern Europe",
    "layers": 14,
    "incidents": 28,
    "incLayers": 5,
    "readings": 17,
    "readLayers": 4,
    "assets": 97,
    "assetLayers": 5
  },
  {
    "iso2": "CN",
    "name": "China",
    "subregion": "Eastern Asia",
    "layers": 13,
    "incidents": 5,
    "incLayers": 3,
    "readings": 81,
    "readLayers": 4,
    "assets": 162,
    "assetLayers": 6
  },
  {
    "iso2": "BR",
    "name": "Brazil",
    "subregion": "South America",
    "layers": 13,
    "incidents": 4,
    "incLayers": 3,
    "readings": 6,
    "readLayers": 4,
    "assets": 132,
    "assetLayers": 6
  },
  {
    "iso2": "PH",
    "name": "Philippines",
    "subregion": "South-Eastern Asia",
    "layers": 13,
    "incidents": 13,
    "incLayers": 4,
    "readings": 6,
    "readLayers": 5,
    "assets": 112,
    "assetLayers": 4
  },
  {
    "iso2": "MX",
    "name": "Mexico",
    "subregion": "Central America",
    "layers": 13,
    "incidents": 49,
    "incLayers": 4,
    "readings": 10,
    "readLayers": 4,
    "assets": 56,
    "assetLayers": 5
  },
  {
    "iso2": "SE",
    "name": "Sweden",
    "subregion": "Northern Europe",
    "layers": 13,
    "incidents": 13,
    "incLayers": 3,
    "readings": 7,
    "readLayers": 4,
    "assets": 69,
    "assetLayers": 6
  },
  {
    "iso2": "AR",
    "name": "Argentina",
    "subregion": "South America",
    "layers": 13,
    "incidents": 28,
    "incLayers": 4,
    "readings": 5,
    "readLayers": 4,
    "assets": 27,
    "assetLayers": 5
  },
  {
    "iso2": "AE",
    "name": "United Arab Emirates",
    "subregion": "Western Asia",
    "layers": 13,
    "incidents": 12,
    "incLayers": 4,
    "readings": 4,
    "readLayers": 4,
    "assets": 41,
    "assetLayers": 5
  },
  {
    "iso2": "CO",
    "name": "Colombia",
    "subregion": "South America",
    "layers": 13,
    "incidents": 6,
    "incLayers": 5,
    "readings": 5,
    "readLayers": 4,
    "assets": 30,
    "assetLayers": 4
  },
  {
    "iso2": "KR",
    "name": "Korea, Republic of",
    "subregion": "Eastern Asia",
    "layers": 12,
    "incidents": 4,
    "incLayers": 2,
    "readings": 235,
    "readLayers": 4,
    "assets": 39,
    "assetLayers": 6
  },
  {
    "iso2": "CA",
    "name": "Canada",
    "subregion": "Northern America",
    "layers": 12,
    "incidents": 1,
    "incLayers": 1,
    "readings": 58,
    "readLayers": 6,
    "assets": 202,
    "assetLayers": 5
  },
  {
    "iso2": "IT",
    "name": "Italy",
    "subregion": "Southern Europe",
    "layers": 12,
    "incidents": 18,
    "incLayers": 4,
    "readings": 8,
    "readLayers": 4,
    "assets": 119,
    "assetLayers": 4
  },
  {
    "iso2": "ZA",
    "name": "South Africa",
    "subregion": "Southern Africa",
    "layers": 12,
    "incidents": 5,
    "incLayers": 3,
    "readings": 17,
    "readLayers": 4,
    "assets": 36,
    "assetLayers": 5
  },
  {
    "iso2": "PL",
    "name": "Poland",
    "subregion": "Eastern Europe",
    "layers": 12,
    "incidents": 33,
    "incLayers": 5,
    "readings": 8,
    "readLayers": 3,
    "assets": 14,
    "assetLayers": 4
  },
  {
    "iso2": "PK",
    "name": "Pakistan",
    "subregion": "Southern Asia",
    "layers": 12,
    "incidents": 11,
    "incLayers": 4,
    "readings": 3,
    "readLayers": 3,
    "assets": 29,
    "assetLayers": 5
  },
  {
    "iso2": "ID",
    "name": "Indonesia",
    "subregion": "South-Eastern Asia",
    "layers": 11,
    "incidents": 67,
    "incLayers": 5,
    "readings": 3,
    "readLayers": 3,
    "assets": 225,
    "assetLayers": 3
  },
  {
    "iso2": "DE",
    "name": "Germany",
    "subregion": "Western Europe",
    "layers": 11,
    "incidents": 19,
    "incLayers": 3,
    "readings": 37,
    "readLayers": 4,
    "assets": 44,
    "assetLayers": 4
  },
  {
    "iso2": "CL",
    "name": "Chile",
    "subregion": "South America",
    "layers": 11,
    "incidents": 48,
    "incLayers": 3,
    "readings": 7,
    "readLayers": 4,
    "assets": 38,
    "assetLayers": 4
  },
  {
    "iso2": "GR",
    "name": "Greece",
    "subregion": "Southern Europe",
    "layers": 11,
    "incidents": 14,
    "incLayers": 4,
    "readings": 3,
    "readLayers": 3,
    "assets": 56,
    "assetLayers": 4
  },
  {
    "iso2": "RO",
    "name": "Romania",
    "subregion": "Eastern Europe",
    "layers": 11,
    "incidents": 19,
    "incLayers": 4,
    "readings": 7,
    "readLayers": 3,
    "assets": 15,
    "assetLayers": 4
  },
  {
    "iso2": "UA",
    "name": "Ukraine",
    "subregion": "Eastern Europe",
    "layers": 11,
    "incidents": 5,
    "incLayers": 4,
    "readings": 3,
    "readLayers": 3,
    "assets": 11,
    "assetLayers": 4
  },
  {
    "iso2": "MY",
    "name": "Malaysia",
    "subregion": "South-Eastern Asia",
    "layers": 10,
    "incidents": 5,
    "incLayers": 3,
    "readings": 3,
    "readLayers": 3,
    "assets": 112,
    "assetLayers": 4
  },
  {
    "iso2": "SA",
    "name": "Saudi Arabia",
    "subregion": "Western Asia",
    "layers": 10,
    "incidents": 16,
    "incLayers": 3,
    "readings": 3,
    "readLayers": 3,
    "assets": 49,
    "assetLayers": 4
  },
  {
    "iso2": "TH",
    "name": "Thailand",
    "subregion": "South-Eastern Asia",
    "layers": 10,
    "incidents": 6,
    "incLayers": 2,
    "readings": 24,
    "readLayers": 4,
    "assets": 34,
    "assetLayers": 4
  },
  {
    "iso2": "KZ",
    "name": "Kazakhstan",
    "subregion": "Central Asia",
    "layers": 10,
    "incidents": 28,
    "incLayers": 3,
    "readings": 3,
    "readLayers": 3,
    "assets": 23,
    "assetLayers": 4
  },
  {
    "iso2": "NZ",
    "name": "New Zealand",
    "subregion": "Australia and New Zealand",
    "layers": 10,
    "incidents": 8,
    "incLayers": 2,
    "readings": 5,
    "readLayers": 3,
    "assets": 40,
    "assetLayers": 5
  },
  {
    "iso2": "NL",
    "name": "Netherlands",
    "subregion": "Western Europe",
    "layers": 10,
    "incidents": 7,
    "incLayers": 2,
    "readings": 6,
    "readLayers": 3,
    "assets": 25,
    "assetLayers": 5
  },
  {
    "iso2": "IR",
    "name": "Iran, Islamic Republic of",
    "subregion": "Southern Asia",
    "layers": 10,
    "incidents": 3,
    "incLayers": 3,
    "readings": 3,
    "readLayers": 3,
    "assets": 29,
    "assetLayers": 4
  },
  {
    "iso2": "NG",
    "name": "Nigeria",
    "subregion": "Western Africa",
    "layers": 10,
    "incidents": 2,
    "incLayers": 1,
    "readings": 5,
    "readLayers": 5,
    "assets": 23,
    "assetLayers": 4
  },
  {
    "iso2": "BE",
    "name": "Belgium",
    "subregion": "Western Europe",
    "layers": 10,
    "incidents": 7,
    "incLayers": 2,
    "readings": 5,
    "readLayers": 3,
    "assets": 13,
    "assetLayers": 5
  },
  {
    "iso2": "KE",
    "name": "Kenya",
    "subregion": "Eastern Africa",
    "layers": 10,
    "incidents": 2,
    "incLayers": 2,
    "readings": 4,
    "readLayers": 4,
    "assets": 17,
    "assetLayers": 4
  },
  {
    "iso2": "AU",
    "name": "Australia",
    "subregion": "Australia and New Zealand",
    "layers": 9,
    "incidents": 7,
    "incLayers": 2,
    "readings": 17,
    "readLayers": 3,
    "assets": 80,
    "assetLayers": 4
  },
  {
    "iso2": "FI",
    "name": "Finland",
    "subregion": "Northern Europe",
    "layers": 9,
    "incidents": 24,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 38,
    "assetLayers": 4
  },
  {
    "iso2": "EG",
    "name": "Egypt",
    "subregion": "Northern Africa",
    "layers": 9,
    "incidents": 4,
    "incLayers": 2,
    "readings": 3,
    "readLayers": 3,
    "assets": 50,
    "assetLayers": 4
  },
  {
    "iso2": "PE",
    "name": "Peru",
    "subregion": "South America",
    "layers": 9,
    "incidents": 1,
    "incLayers": 1,
    "readings": 23,
    "readLayers": 4,
    "assets": 17,
    "assetLayers": 4
  },
  {
    "iso2": "VE",
    "name": "Venezuela, Bolivarian Republic of",
    "subregion": "South America",
    "layers": 9,
    "incidents": 4,
    "incLayers": 4,
    "readings": 2,
    "readLayers": 2,
    "assets": 27,
    "assetLayers": 3
  },
  {
    "iso2": "BG",
    "name": "Bulgaria",
    "subregion": "Eastern Europe",
    "layers": 9,
    "incidents": 5,
    "incLayers": 2,
    "readings": 4,
    "readLayers": 3,
    "assets": 11,
    "assetLayers": 4
  },
  {
    "iso2": "BD",
    "name": "Bangladesh",
    "subregion": "Southern Asia",
    "layers": 9,
    "incidents": 3,
    "incLayers": 1,
    "readings": 3,
    "readLayers": 3,
    "assets": 11,
    "assetLayers": 5
  },
  {
    "iso2": "GT",
    "name": "Guatemala",
    "subregion": "Central America",
    "layers": 9,
    "incidents": 5,
    "incLayers": 4,
    "readings": 2,
    "readLayers": 2,
    "assets": 9,
    "assetLayers": 3
  },
  {
    "iso2": "SY",
    "name": "Syrian Arab Republic",
    "subregion": "Western Asia",
    "layers": 9,
    "incidents": 4,
    "incLayers": 4,
    "readings": 2,
    "readLayers": 2,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "NO",
    "name": "Norway",
    "subregion": "Northern Europe",
    "layers": 8,
    "incidents": 6,
    "incLayers": 2,
    "readings": 6,
    "readLayers": 3,
    "assets": 69,
    "assetLayers": 3
  },
  {
    "iso2": "IE",
    "name": "Ireland",
    "subregion": "Northern Europe",
    "layers": 8,
    "incidents": 3,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 34,
    "assetLayers": 3
  },
  {
    "iso2": "LT",
    "name": "Lithuania",
    "subregion": "Northern Europe",
    "layers": 8,
    "incidents": 28,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "OM",
    "name": "Oman",
    "subregion": "Western Asia",
    "layers": 8,
    "incidents": 3,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 32,
    "assetLayers": 4
  },
  {
    "iso2": "MZ",
    "name": "Mozambique",
    "subregion": "Eastern Africa",
    "layers": 8,
    "incidents": 19,
    "incLayers": 2,
    "readings": 3,
    "readLayers": 3,
    "assets": 11,
    "assetLayers": 3
  },
  {
    "iso2": "YE",
    "name": "Yemen",
    "subregion": "Western Asia",
    "layers": 8,
    "incidents": 8,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 22,
    "assetLayers": 3
  },
  {
    "iso2": "LY",
    "name": "Libyan Arab Jamahiriya",
    "subregion": "Northern Africa",
    "layers": 8,
    "incidents": 5,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 24,
    "assetLayers": 3
  },
  {
    "iso2": "IL",
    "name": "Israel",
    "subregion": "Western Asia",
    "layers": 8,
    "incidents": 3,
    "incLayers": 1,
    "readings": 4,
    "readLayers": 4,
    "assets": 17,
    "assetLayers": 3
  },
  {
    "iso2": "GE",
    "name": "Georgia",
    "subregion": "Western Asia",
    "layers": 8,
    "incidents": 12,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 7,
    "assetLayers": 3
  },
  {
    "iso2": "HR",
    "name": "Croatia",
    "subregion": "Southern Europe",
    "layers": 8,
    "incidents": 2,
    "incLayers": 2,
    "readings": 6,
    "readLayers": 3,
    "assets": 10,
    "assetLayers": 3
  },
  {
    "iso2": "CZ",
    "name": "Czech Republic",
    "subregion": "Eastern Europe",
    "layers": 8,
    "incidents": 5,
    "incLayers": 3,
    "readings": 6,
    "readLayers": 3,
    "assets": 7,
    "assetLayers": 2
  },
  {
    "iso2": "IQ",
    "name": "Iraq",
    "subregion": "Western Asia",
    "layers": 8,
    "incidents": 2,
    "incLayers": 2,
    "readings": 3,
    "readLayers": 3,
    "assets": 11,
    "assetLayers": 3
  },
  {
    "iso2": "CR",
    "name": "Costa Rica",
    "subregion": "Central America",
    "layers": 8,
    "incidents": 5,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "LB",
    "name": "Lebanon",
    "subregion": "Western Asia",
    "layers": 8,
    "incidents": 3,
    "incLayers": 2,
    "readings": 3,
    "readLayers": 3,
    "assets": 9,
    "assetLayers": 3
  },
  {
    "iso2": "NI",
    "name": "Nicaragua",
    "subregion": "Central America",
    "layers": 8,
    "incidents": 5,
    "incLayers": 4,
    "readings": 1,
    "readLayers": 1,
    "assets": 4,
    "assetLayers": 3
  },
  {
    "iso2": "GM",
    "name": "Gambia",
    "subregion": "Western Africa",
    "layers": 8,
    "incidents": 2,
    "incLayers": 2,
    "readings": 3,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 3
  },
  {
    "iso2": "DK",
    "name": "Denmark",
    "subregion": "Northern Europe",
    "layers": 7,
    "incidents": 9,
    "incLayers": 3,
    "readings": 1,
    "readLayers": 1,
    "assets": 62,
    "assetLayers": 3
  },
  {
    "iso2": "MM",
    "name": "Myanmar",
    "subregion": "South-Eastern Asia",
    "layers": 7,
    "incidents": 55,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "CN-TW",
    "name": "Taiwan",
    "subregion": "Eastern Asia",
    "layers": 7,
    "incidents": 2,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 1,
    "assets": 44,
    "assetLayers": 5
  },
  {
    "iso2": "PT",
    "name": "Portugal",
    "subregion": "Southern Europe",
    "layers": 7,
    "incidents": 2,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 39,
    "assetLayers": 3
  },
  {
    "iso2": "MA",
    "name": "Morocco",
    "subregion": "Northern Africa",
    "layers": 7,
    "incidents": 1,
    "incLayers": 1,
    "readings": 3,
    "readLayers": 3,
    "assets": 29,
    "assetLayers": 3
  },
  {
    "iso2": "LV",
    "name": "Latvia",
    "subregion": "Northern Europe",
    "layers": 7,
    "incidents": 18,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "PG",
    "name": "Papua New Guinea",
    "subregion": "Melanesia",
    "layers": 7,
    "incidents": 3,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 22,
    "assetLayers": 3
  },
  {
    "iso2": "EE",
    "name": "Estonia",
    "subregion": "Northern Europe",
    "layers": 7,
    "incidents": 10,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 14,
    "assetLayers": 3
  },
  {
    "iso2": "PA",
    "name": "Panama",
    "subregion": "Central America",
    "layers": 7,
    "incidents": 2,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 20,
    "assetLayers": 4
  },
  {
    "iso2": "VN",
    "name": "Viet Nam",
    "subregion": "South-Eastern Asia",
    "layers": 7,
    "incidents": 0,
    "incLayers": 0,
    "readings": 5,
    "readLayers": 4,
    "assets": 19,
    "assetLayers": 3
  },
  {
    "iso2": "DJ",
    "name": "Djibouti",
    "subregion": "Eastern Africa",
    "layers": 7,
    "incidents": 2,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 19,
    "assetLayers": 3
  },
  {
    "iso2": "AL",
    "name": "Albania",
    "subregion": "Southern Europe",
    "layers": 7,
    "incidents": 5,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 15,
    "assetLayers": 3
  },
  {
    "iso2": "AO",
    "name": "Angola",
    "subregion": "Middle Africa",
    "layers": 7,
    "incidents": 4,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 14,
    "assetLayers": 3
  },
  {
    "iso2": "LK",
    "name": "Sri Lanka",
    "subregion": "Southern Asia",
    "layers": 7,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 17,
    "assetLayers": 4
  },
  {
    "iso2": "EC",
    "name": "Ecuador",
    "subregion": "South America",
    "layers": 7,
    "incidents": 2,
    "incLayers": 1,
    "readings": 3,
    "readLayers": 3,
    "assets": 13,
    "assetLayers": 3
  },
  {
    "iso2": "CD",
    "name": "Congo, the Democratic Republic of the",
    "subregion": "Middle Africa",
    "layers": 7,
    "incidents": 5,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 10,
    "assetLayers": 3
  },
  {
    "iso2": "SO",
    "name": "Somalia",
    "subregion": "Eastern Africa",
    "layers": 7,
    "incidents": 7,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "GH",
    "name": "Ghana",
    "subregion": "Western Africa",
    "layers": 7,
    "incidents": 2,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 10,
    "assetLayers": 3
  },
  {
    "iso2": "SN",
    "name": "Senegal",
    "subregion": "Western Africa",
    "layers": 7,
    "incidents": 1,
    "incLayers": 1,
    "readings": 5,
    "readLayers": 3,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "TN",
    "name": "Tunisia",
    "subregion": "Northern Africa",
    "layers": 7,
    "incidents": 1,
    "incLayers": 1,
    "readings": 3,
    "readLayers": 3,
    "assets": 10,
    "assetLayers": 3
  },
  {
    "iso2": "SD",
    "name": "Sudan",
    "subregion": "Northern Africa",
    "layers": 7,
    "incidents": 2,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "CH",
    "name": "Switzerland",
    "subregion": "Western Europe",
    "layers": 7,
    "incidents": 5,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 2
  },
  {
    "iso2": "AF",
    "name": "Afghanistan",
    "subregion": "Southern Asia",
    "layers": 7,
    "incidents": 5,
    "incLayers": 4,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "AZ",
    "name": "Azerbaijan",
    "subregion": "Western Asia",
    "layers": 7,
    "incidents": 3,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 3
  },
  {
    "iso2": "VU",
    "name": "Vanuatu",
    "subregion": "Melanesia",
    "layers": 7,
    "incidents": 3,
    "incLayers": 3,
    "readings": 2,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 2
  },
  {
    "iso2": "AM",
    "name": "Armenia",
    "subregion": "Western Asia",
    "layers": 6,
    "incidents": 3,
    "incLayers": 1,
    "readings": 30,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 2
  },
  {
    "iso2": "DZ",
    "name": "Algeria",
    "subregion": "Northern Africa",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 24,
    "assetLayers": 3
  },
  {
    "iso2": "DO",
    "name": "Dominican Republic",
    "subregion": "Caribbean",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 19,
    "assetLayers": 3
  },
  {
    "iso2": "CY",
    "name": "Cyprus",
    "subregion": "Western Asia",
    "layers": 6,
    "incidents": 4,
    "incLayers": 2,
    "readings": 1,
    "readLayers": 1,
    "assets": 16,
    "assetLayers": 3
  },
  {
    "iso2": "QA",
    "name": "Qatar",
    "subregion": "Western Asia",
    "layers": 6,
    "incidents": 3,
    "incLayers": 1,
    "readings": 1,
    "readLayers": 1,
    "assets": 17,
    "assetLayers": 4
  },
  {
    "iso2": "FJ",
    "name": "Fiji",
    "subregion": "Melanesia",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 14,
    "assetLayers": 3
  },
  {
    "iso2": "JO",
    "name": "Jordan",
    "subregion": "Western Asia",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 13,
    "assetLayers": 3
  },
  {
    "iso2": "CM",
    "name": "Cameroon",
    "subregion": "Middle Africa",
    "layers": 6,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 12,
    "assetLayers": 3
  },
  {
    "iso2": "KW",
    "name": "Kuwait",
    "subregion": "Western Asia",
    "layers": 6,
    "incidents": 4,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 9,
    "assetLayers": 3
  },
  {
    "iso2": "MG",
    "name": "Madagascar",
    "subregion": "Eastern Africa",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 12,
    "assetLayers": 3
  },
  {
    "iso2": "GA",
    "name": "Gabon",
    "subregion": "Middle Africa",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 10,
    "assetLayers": 3
  },
  {
    "iso2": "TZ",
    "name": "Tanzania, United Republic of",
    "subregion": "Eastern Africa",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 10,
    "assetLayers": 3
  },
  {
    "iso2": "KH",
    "name": "Cambodia",
    "subregion": "South-Eastern Asia",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 9,
    "assetLayers": 3
  },
  {
    "iso2": "IS",
    "name": "Iceland",
    "subregion": "Northern Europe",
    "layers": 6,
    "incidents": 2,
    "incLayers": 2,
    "readings": 1,
    "readLayers": 1,
    "assets": 9,
    "assetLayers": 3
  },
  {
    "iso2": "HN",
    "name": "Honduras",
    "subregion": "Central America",
    "layers": 6,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "NP",
    "name": "Nepal",
    "subregion": "Southern Asia",
    "layers": 6,
    "incidents": 3,
    "incLayers": 2,
    "readings": 5,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "ET",
    "name": "Ethiopia",
    "subregion": "Eastern Africa",
    "layers": 6,
    "incidents": 3,
    "incLayers": 2,
    "readings": 3,
    "readLayers": 3,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "UY",
    "name": "Uruguay",
    "subregion": "South America",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 7,
    "assetLayers": 3
  },
  {
    "iso2": "CG",
    "name": "Congo",
    "subregion": "Middle Africa",
    "layers": 6,
    "incidents": 2,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 3
  },
  {
    "iso2": "LR",
    "name": "Liberia",
    "subregion": "Western Africa",
    "layers": 6,
    "incidents": 0,
    "incLayers": 0,
    "readings": 6,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 3
  },
  {
    "iso2": "MR",
    "name": "Mauritania",
    "subregion": "Western Africa",
    "layers": 6,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 6,
    "assetLayers": 3
  },
  {
    "iso2": "GY",
    "name": "Guyana",
    "subregion": "South America",
    "layers": 6,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 5,
    "assetLayers": 3
  },
  {
    "iso2": "RS",
    "name": "Serbia",
    "subregion": "Southern Europe",
    "layers": 6,
    "incidents": 3,
    "incLayers": 2,
    "readings": 3,
    "readLayers": 3,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "GN",
    "name": "Guinea",
    "subregion": "Western Africa",
    "layers": 6,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 3
  },
  {
    "iso2": "BS",
    "name": "Bahamas",
    "subregion": "Caribbean",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 30,
    "assetLayers": 3
  },
  {
    "iso2": "PR",
    "name": "Puerto Rico",
    "subregion": "Caribbean",
    "layers": 5,
    "incidents": 6,
    "incLayers": 2,
    "readings": 0,
    "readLayers": 0,
    "assets": 21,
    "assetLayers": 3
  },
  {
    "iso2": "CU",
    "name": "Cuba",
    "subregion": "Caribbean",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 16,
    "assetLayers": 3
  },
  {
    "iso2": "AT",
    "name": "Austria",
    "subregion": "Western Europe",
    "layers": 5,
    "incidents": 4,
    "incLayers": 2,
    "readings": 6,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 1
  },
  {
    "iso2": "TT",
    "name": "Trinidad and Tobago",
    "subregion": "Caribbean",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 11,
    "assetLayers": 3
  },
  {
    "iso2": "BY",
    "name": "Belarus",
    "subregion": "Eastern Europe",
    "layers": 5,
    "incidents": 7,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 2
  },
  {
    "iso2": "CI",
    "name": "Côte d'Ivoire",
    "subregion": "Western Africa",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 9,
    "assetLayers": 3
  },
  {
    "iso2": "SL",
    "name": "Sierra Leone",
    "subregion": "Western Africa",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 8,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 3
  },
  {
    "iso2": "SB",
    "name": "Solomon Islands",
    "subregion": "Melanesia",
    "layers": 5,
    "incidents": 1,
    "incLayers": 1,
    "readings": 1,
    "readLayers": 1,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "HU",
    "name": "Hungary",
    "subregion": "Eastern Europe",
    "layers": 5,
    "incidents": 2,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 2
  },
  {
    "iso2": "UG",
    "name": "Uganda",
    "subregion": "Eastern Africa",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 7,
    "assetLayers": 3
  },
  {
    "iso2": "BZ",
    "name": "Belize",
    "subregion": "Central America",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 3
  },
  {
    "iso2": "BA",
    "name": "Bosnia and Herzegovina",
    "subregion": "Southern Europe",
    "layers": 5,
    "incidents": 2,
    "incLayers": 2,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "HT",
    "name": "Haiti",
    "subregion": "Caribbean",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 3
  },
  {
    "iso2": "LA",
    "name": "Lao People's Democratic Republic",
    "subregion": "South-Eastern Asia",
    "layers": 5,
    "incidents": 1,
    "incLayers": 1,
    "readings": 4,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "SR",
    "name": "Suriname",
    "subregion": "South America",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 3
  },
  {
    "iso2": "TG",
    "name": "Togo",
    "subregion": "Western Africa",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 3
  },
  {
    "iso2": "BJ",
    "name": "Benin",
    "subregion": "Western Africa",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 3
  },
  {
    "iso2": "NA",
    "name": "Namibia",
    "subregion": "Southern Africa",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 3
  },
  {
    "iso2": "SK",
    "name": "Slovakia",
    "subregion": "Eastern Europe",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 4,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 2
  },
  {
    "iso2": "MW",
    "name": "Malawi",
    "subregion": "Eastern Africa",
    "layers": 5,
    "incidents": 1,
    "incLayers": 1,
    "readings": 3,
    "readLayers": 3,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "SI",
    "name": "Slovenia",
    "subregion": "Southern Europe",
    "layers": 5,
    "incidents": 1,
    "incLayers": 1,
    "readings": 3,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 2
  },
  {
    "iso2": "GW",
    "name": "Guinea-Bissau",
    "subregion": "Western Africa",
    "layers": 5,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 3
  },
  {
    "iso2": "AQ",
    "name": "Antarctica",
    "subregion": "Antarctica",
    "layers": 4,
    "incidents": 15,
    "incLayers": 1,
    "readings": 106,
    "readLayers": 3,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "JM",
    "name": "Jamaica",
    "subregion": "Caribbean",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 17,
    "assetLayers": 3
  },
  {
    "iso2": "CV",
    "name": "Cape Verde",
    "subregion": "",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 10,
    "assetLayers": 1
  },
  {
    "iso2": "BN",
    "name": "Brunei Darussalam",
    "subregion": "South-Eastern Asia",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 10,
    "assetLayers": 3
  },
  {
    "iso2": "GL",
    "name": "Greenland",
    "subregion": "Northern America",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 1,
    "assets": 8,
    "assetLayers": 3
  },
  {
    "iso2": "BO",
    "name": "Bolivia, Plurinational State of",
    "subregion": "South America",
    "layers": 4,
    "incidents": 2,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 1
  },
  {
    "iso2": "ZM",
    "name": "Zambia",
    "subregion": "Eastern Africa",
    "layers": 4,
    "incidents": 5,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "MP",
    "name": "Northern Mariana Islands",
    "subregion": "",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 1
  },
  {
    "iso2": "GQ",
    "name": "Equatorial Guinea",
    "subregion": "Middle Africa",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 7,
    "assetLayers": 3
  },
  {
    "iso2": "KP",
    "name": "Korea, Democratic People's Republic of",
    "subregion": "Eastern Asia",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 2,
    "assets": 5,
    "assetLayers": 2
  },
  {
    "iso2": "MD",
    "name": "Moldova, Republic of",
    "subregion": "Eastern Europe",
    "layers": 4,
    "incidents": 5,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "BW",
    "name": "Botswana",
    "subregion": "Southern Africa",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "BB",
    "name": "Barbados",
    "subregion": "",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "N. Cyprus",
    "name": "N. Cyprus",
    "subregion": "Western Asia",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 0,
    "readLayers": 0,
    "assets": 5,
    "assetLayers": 3
  },
  {
    "iso2": "PY",
    "name": "Paraguay",
    "subregion": "South America",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "TL",
    "name": "Timor-Leste",
    "subregion": "South-Eastern Asia",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 5,
    "assetLayers": 3
  },
  {
    "iso2": "AS",
    "name": "American Samoa",
    "subregion": "",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "ME",
    "name": "Montenegro",
    "subregion": "Southern Europe",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "NR",
    "name": "Nauru",
    "subregion": "",
    "layers": 4,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "NE",
    "name": "Niger",
    "subregion": "Western Africa",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "SS",
    "name": "South Sudan",
    "subregion": "Eastern Africa",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "SZ",
    "name": "Swaziland",
    "subregion": "Southern Africa",
    "layers": 4,
    "incidents": 1,
    "incLayers": 1,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "NC",
    "name": "New Caledonia",
    "subregion": "Melanesia",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 13,
    "assetLayers": 3
  },
  {
    "iso2": "UZ",
    "name": "Uzbekistan",
    "subregion": "Central Asia",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 6,
    "assetLayers": 1
  },
  {
    "iso2": "Somaliland",
    "name": "Somaliland",
    "subregion": "Eastern Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 7,
    "assetLayers": 3
  },
  {
    "iso2": "KM",
    "name": "Comoros",
    "subregion": "",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "ER",
    "name": "Eritrea",
    "subregion": "Eastern Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "MU",
    "name": "Mauritius",
    "subregion": "",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "TJ",
    "name": "Tajikistan",
    "subregion": "Central Asia",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "ZW",
    "name": "Zimbabwe",
    "subregion": "Eastern Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "AG",
    "name": "Antigua and Barbuda",
    "subregion": "",
    "layers": 3,
    "incidents": 1,
    "incLayers": 1,
    "readings": 1,
    "readLayers": 1,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "BH",
    "name": "Bahrain",
    "subregion": "",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "KG",
    "name": "Kyrgyzstan",
    "subregion": "Central Asia",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "TO",
    "name": "Tonga",
    "subregion": "",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "TM",
    "name": "Turkmenistan",
    "subregion": "Central Asia",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "BF",
    "name": "Burkina Faso",
    "subregion": "Western Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "DM",
    "name": "Dominica",
    "subregion": "",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "MK",
    "name": "Macedonia, the former Yugoslav Republic of",
    "subregion": "Southern Europe",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "ML",
    "name": "Mali",
    "subregion": "Western Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "MN",
    "name": "Mongolia",
    "subregion": "Eastern Asia",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "KN",
    "name": "Saint Kitts and Nevis",
    "subregion": "",
    "layers": 3,
    "incidents": 1,
    "incLayers": 1,
    "readings": 1,
    "readLayers": 1,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "LC",
    "name": "Saint Lucia",
    "subregion": "",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "BT",
    "name": "Bhutan",
    "subregion": "Southern Asia",
    "layers": 3,
    "incidents": 1,
    "incLayers": 1,
    "readings": 1,
    "readLayers": 1,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "BI",
    "name": "Burundi",
    "subregion": "Eastern Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "CF",
    "name": "Central African Republic",
    "subregion": "Middle Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "TD",
    "name": "Chad",
    "subregion": "Middle Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "SV",
    "name": "El Salvador",
    "subregion": "Central America",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "HK",
    "name": "Hong Kong",
    "subregion": "",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 3,
    "readLayers": 3,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "PS",
    "name": "Palestinian Territory, Occupied",
    "subregion": "Western Asia",
    "layers": 3,
    "incidents": 2,
    "incLayers": 2,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "RW",
    "name": "Rwanda",
    "subregion": "Eastern Africa",
    "layers": 3,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "MT",
    "name": "Malta",
    "subregion": "",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 7,
    "assetLayers": 1
  },
  {
    "iso2": "VC",
    "name": "Saint Vincent and the Grenadines",
    "subregion": "",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 7,
    "assetLayers": 1
  },
  {
    "iso2": "BM",
    "name": "Bermuda",
    "subregion": "",
    "layers": 2,
    "incidents": 1,
    "incLayers": 1,
    "readings": 0,
    "readLayers": 0,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "GD",
    "name": "Grenada",
    "subregion": "",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "KY",
    "name": "Cayman Islands",
    "subregion": "",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "XK",
    "name": "Kosovo",
    "subregion": "Southern Europe",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 1,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "MH",
    "name": "Marshall Islands",
    "subregion": "",
    "layers": 2,
    "incidents": 1,
    "incLayers": 1,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "MQ",
    "name": "Martinique",
    "subregion": "",
    "layers": 2,
    "incidents": 1,
    "incLayers": 1,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "WS",
    "name": "Samoa",
    "subregion": "",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "LS",
    "name": "Lesotho",
    "subregion": "Southern Africa",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "LU",
    "name": "Luxembourg",
    "subregion": "Western Europe",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 2,
    "readLayers": 2,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "TC",
    "name": "Turks and Caicos Islands",
    "subregion": "",
    "layers": 2,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "PF",
    "name": "French Polynesia",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 23,
    "assetLayers": 1
  },
  {
    "iso2": "MV",
    "name": "Maldives",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 17,
    "assetLayers": 1
  },
  {
    "iso2": "VI",
    "name": "Virgin Islands, U.S.",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 10,
    "assetLayers": 1
  },
  {
    "iso2": "GP",
    "name": "Guadeloupe",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 9,
    "assetLayers": 1
  },
  {
    "iso2": "GU",
    "name": "Guam",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 5,
    "assetLayers": 1
  },
  {
    "iso2": "IM",
    "name": "Isle of Man",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 5,
    "assetLayers": 1
  },
  {
    "iso2": "GG",
    "name": "Guernsey",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 4,
    "assetLayers": 1
  },
  {
    "iso2": "RE",
    "name": "Réunion",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "TK",
    "name": "Tokelau",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 3,
    "assetLayers": 1
  },
  {
    "iso2": "AW",
    "name": "Aruba",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "CK",
    "name": "Cook Islands",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "CW",
    "name": "Curaçao",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "FO",
    "name": "Faroe Islands",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "JE",
    "name": "Jersey",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "KI",
    "name": "Kiribati",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "YT",
    "name": "Mayotte",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "BL",
    "name": "Saint Barthélemy",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "SC",
    "name": "Seychelles",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "WF",
    "name": "Wallis and Futuna",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 2,
    "assetLayers": 1
  },
  {
    "iso2": "AI",
    "name": "Anguilla",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "IO",
    "name": "British Indian Ocean Territory",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "CX",
    "name": "Christmas Island",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "CC",
    "name": "Cocos (Keeling) Islands",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "GF",
    "name": "French Guiana",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "LI",
    "name": "Liechtenstein",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "MC",
    "name": "Monaco",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "MS",
    "name": "Montserrat",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "NU",
    "name": "Niue",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "PW",
    "name": "Palau",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "SH",
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "PM",
    "name": "Saint Pierre and Miquelon",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "ST",
    "name": "Sao Tome and Principe",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "SG",
    "name": "Singapore",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "SX",
    "name": "Sint Maarten (Dutch part)",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "TW",
    "name": "Taiwan, Province of China",
    "subregion": "",
    "layers": 1,
    "incidents": 1,
    "incLayers": 1,
    "readings": 0,
    "readLayers": 0,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "TV",
    "name": "Tuvalu",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 0,
    "readLayers": 0,
    "assets": 1,
    "assetLayers": 1
  },
  {
    "iso2": "VG",
    "name": "Virgin Islands, British",
    "subregion": "",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  },
  {
    "iso2": "EH",
    "name": "Western Sahara",
    "subregion": "Northern Africa",
    "layers": 1,
    "incidents": 0,
    "incLayers": 0,
    "readings": 1,
    "readLayers": 1,
    "assets": 0,
    "assetLayers": 0
  }
];

export const AUDIT_TIERS: AuditTierTotal[] = [
  {
    "tier": "incidents",
    "countries": 135,
    "features": 3014
  },
  {
    "tier": "readings",
    "countries": 198,
    "features": 1522
  },
  {
    "tier": "assets",
    "countries": 222,
    "features": 3949
  }
];

export const AUDIT_TOTALS = {
  "layers": 34,
  "live": 29,
  "partial": 1,
  "down": 2,
  "locked": 2,
  "featuresServed": 9016,
  "featuresPlaced": 8485,
  "featuresUnplaced": 531,
  "countriesTouched": 235,
  "countriesWithAny": 235,
  "spanningLayers": [
    "Submarine cables",
    "GPS jamming"
  ]
} as const;
