/**
 * GENERATED by `scripts/gen-landing-snapshot.mjs`. Do not hand-edit.
 *
 * What the landing globe draws is one saved snapshot of the live map
 * (`public/marketing/globe-snapshot.json`), not live data. This file carries the
 * snapshot's own date so the page can print it without importing the 472 KB JSON
 * into the server bundle. tests/unit/landing-snapshot.test.ts checks the two agree.
 */
export const GLOBE_SNAPSHOT = {
  takenAt: "2026-10-05T00:45:17.000Z",
  takenFrom: "https://provenance-online.com",
} as const;
