import { notFound } from "next/navigation";

/**
 * The production gate for the curation tools, and the template the promote step writes.
 *
 * BOTH LIVE HERE RATHER THAN IN THE ROUTE FILES because a Next route or layout module
 * may export only the names Next recognises, and `tests/unit/route-export-contract.test.ts`
 * catches that — the failure it prevents is green locally, green in the suite, dead on
 * deploy. It caught both of these before they reached a build, which is the whole
 * reason that test exists.
 */

/**
 * Is this a live deployment?
 *
 * FAILS CLOSED ON EITHER SIGNAL. `NODE_ENV` alone was the first version and one
 * signal is one thing that can be misconfigured: a build run with NODE_ENV unset, a
 * self-hosted runner, a Dockerfile that forgets it. `VERCEL_ENV` is set independently
 * by the platform, so requiring BOTH to say development is the difference between an
 * admin surface that leaks on a misconfiguration and one that does not.
 *
 * The cost of the stricter rule is a developer occasionally having to work out why
 * their production-mode local build 404s. That is a much better afternoon than the
 * other one.
 */
export function isProduction(env: Record<string, string | undefined> = process.env): boolean {
  return env.VERCEL_ENV === "production" || env.NODE_ENV === "production";
}

/** 404 unless this is a development server. Used by every page and layout under /admin. */
export function assertDevOnly(): void {
  if (isProduction()) notFound();
}

/**
 * The header of the generated `lib/sources/discovered.data.ts`.
 *
 * Built by concatenation rather than written as one template literal so the string
 * "export const ADMITTED_FEEDS" never starts a line in a route module — the export
 * contract test reads source text, and a literal that LOOKS like an export is
 * indistinguishable from one to a text parse. Keeping it here also means the file this
 * generates carries the same explanation whether you arrive at it through the
 * generator or through the generated file.
 */
export const PROMOTED_FILE_HEADER = [
  "/**",
  " * Every camera network that discovery proposed and a human admitted.",
  " *",
  " * GENERATED by `POST /api/admin/promote` from `data/discovery/ledger.json`. Edit the",
  " * ledger and re-run rather than editing this file, or the next promotion silently",
  " * reverts you. It is committed rather than built because a camera network appearing on",
  " * the map should be a reviewable diff in a pull request.",
  " *",
  " * THIS FILE IS THE GATE. `lib/sources/discovered.ts` serves exactly what is listed",
  " * here and nothing else, and the only way a row lands here is a reviewer working",
  " * through `/admin/verify` one camera at a time and then pressing promote. There is no",
  " * automatic path from a crawl to a pin on the map, by construction rather than by",
  " * policy.",
  " *",
  " * HOW TO READ A ROW. `review` says who admitted it, when, and how many cameras they",
  " * actually opened — `sampled` counts pictures looked at, not rows validated. `blocked`",
  " * lists native ids a reviewer rejected individually, so one dead camera costs one",
  " * camera rather than the network. `license` is copied from what the operator or its",
  " * catalogue states; where nothing is stated it says so in those words, because a",
  " * licence nobody granted is worse than an absent one.",
  " */",
  "",
  'import type { AdmittedFeed } from "@/lib/discovery/types";',
  "",
  "export" + " const ADMITTED_FEEDS: AdmittedFeed[] = ",
].join("\n");
